from torch import Tensor
import torch
from torch import nn
from torch.nn import functional as F
import torch.utils.checkpoint
import contextlib
import numpy as np

import math
from .stgcn import Graph, get_stgcn_chain
from transformers import MT5ForConditionalGeneration, T5Tokenizer 
import warnings
from peft import get_peft_model, LoraConfig, TaskType

import os
from config import mt5_path
    

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    """Fills the input Tensor with values drawn from a truncated"""
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

class SignetModel(nn.Module):
    def __init__(self, args):
        super(SignetModel, self).__init__()
        self.args = args
        
        self.modes = ['body', 'left', 'right', 'face_all']
        
        self.graph, A = {}, []
        # project (x,y,score) to hidden dim
        hidden_dim = args.hidden_dim
        self.proj_linear = nn.ModuleDict()
        for mode in self.modes:
            self.graph[mode] = Graph(layout=f'{mode}', strategy='distance', max_hop=1)
            A.append(torch.tensor(self.graph[mode].A, dtype=torch.float32, requires_grad=False))
            self.proj_linear[mode] = nn.Linear(3, 64)

        self.gcn_modules = nn.ModuleDict()
        self.fusion_gcn_modules = nn.ModuleDict()
        spatial_kernel_size = A[0].size(0)
        for index, mode in enumerate(self.modes):
            self.gcn_modules[mode], final_dim = get_stgcn_chain(64, 'spatial', (1, spatial_kernel_size), A[index].clone(), True)
            self.fusion_gcn_modules[mode], _ = get_stgcn_chain(final_dim, 'temporal', (5, spatial_kernel_size), A[index].clone(), True)
        
        self.gcn_modules['left'] = self.gcn_modules['right']
        self.fusion_gcn_modules['left'] = self.fusion_gcn_modules['right']
        self.proj_linear['left'] = self.proj_linear['right']

        self.part_para = nn.Parameter(torch.zeros(hidden_dim*len(self.modes)))
        self.pose_proj = nn.Linear(256*4, 768)
        
        self.apply(self._init_weights)
        
        if "CSL" in self.args.dataset:
            self.lang = 'Chinese'
        elif "Phoenix" in self.args.dataset:
            self.lang = 'German'
        else:
            self.lang = 'English'
        

        self.mt5_model = MT5ForConditionalGeneration.from_pretrained(mt5_path)
        self.mt5_tokenizer = T5Tokenizer.from_pretrained(mt5_path, legacy=False)
        if args.use_lora:
            lora_config = LoraConfig(
                            r=args.lora_rank,                         # Rank
                            lora_alpha=args.lora_alpha,               # Scaling factor
                            target_modules=args.lora_target_modules,                # LoRA target layers
                            lora_dropout=args.lora_dropout,
                            bias="none",
                            task_type=TaskType.SEQ_2_SEQ_LM
                        )
            self.mt5_model = get_peft_model(self.mt5_model, lora_config)
            for name, param in self.mt5_model.named_parameters():
                if "lora" in name:
                    param.requires_grad = True
                else:
                    param.requires_grad = False
    
        
    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def maybe_autocast(self, dtype=torch.float32):
        # if on cpu, don't use autocast
        # if on gpu, use autocast with dtype if provided, otherwise use torch.float16
        # enable_autocast = self.device != torch.device("cpu")
        enable_autocast = True

        if enable_autocast:
            return torch.cuda.amp.autocast(dtype=dtype)
        else:
            return contextlib.nullcontext()


    def forward(self, src_input, tgt_input):
        
        # Pose branch forward
        features = []
        pool_features_dict = {}  # Store pool features for each body part

        body_feat = None
        for part in self.modes:
            # project position to hidden dim
            proj_feat = self.proj_linear[part](src_input[part]).permute(0,3,1,2) #B,C,T,V
            # spatial gcn forward
            gcn_feat = self.gcn_modules[part](proj_feat)
            if part == 'body':
                body_feat = gcn_feat

            else:
                assert not body_feat is None
                if part == 'left':
                        
                    gcn_feat = gcn_feat + body_feat[..., -2][...,None].detach()
                    
                elif part == 'right':
                        
                    gcn_feat = gcn_feat + body_feat[..., -1][...,None].detach()

                elif part == 'face_all':
                    gcn_feat = gcn_feat + body_feat[..., 0][...,None].detach()

                else:
                    raise NotImplementedError
            
            # temporal gcn forward
            gcn_feat = self.fusion_gcn_modules[part](gcn_feat) #B,C,T,V
            pool_feat = gcn_feat.mean(-1).transpose(1,2) #B,T,C
            
            # Store pool feature for this body part
            pool_features_dict[part] = pool_feat
            features.append(pool_feat)

        # concat sub-pose feature across token dimension
        inputs_embeds = torch.cat(features, dim=-1) + self.part_para
        inputs_embeds = self.pose_proj(inputs_embeds)

        prefix_token = self.mt5_tokenizer(
                                [f"Translate sign language video to {self.lang}: "] * len(tgt_input["gt_sentence"]),
                                padding="longest",
                                truncation=True,
                                return_tensors="pt",
                            ).to(inputs_embeds.device)

        prefix_embeds = self.mt5_model.encoder.embed_tokens(prefix_token['input_ids'])
        inputs_embeds_prefix = torch.cat([prefix_embeds, inputs_embeds], dim=1)

        attention_mask = torch.cat([prefix_token['attention_mask'],
                                    src_input['attention_mask']], dim=1)

        tgt_input_tokenizer = self.mt5_tokenizer(tgt_input['gt_sentence'], 
                                                return_tensors="pt", 
                                                padding=True,
                                                truncation=True,
                                                max_length=50)

        labels = tgt_input_tokenizer['input_ids']
        labels[labels == self.mt5_tokenizer.pad_token_id] = -100
        
        out = self.mt5_model(inputs_embeds = inputs_embeds_prefix,
                    attention_mask = attention_mask,
                    labels = labels.to(inputs_embeds_prefix.device),
                    return_dict = True,
                    )
        
        label = labels.reshape(-1)
        out_logits = out['logits']
        logits = out_logits.reshape(-1,out_logits.shape[-1])
        loss_fct = torch.nn.CrossEntropyLoss(label_smoothing=self.args.label_smoothing, ignore_index=-100)
        loss = loss_fct(logits, label.to(out_logits.device, non_blocking=True))

        stack_out = {
            # use for inference
            'inputs_embeds':inputs_embeds_prefix,
            'attention_mask':attention_mask,
            'loss':loss,
            'pool_features': pool_features_dict,  # Dictionary with pool features for each body part
            'inputs_embeds_after_pose_proj': inputs_embeds,
        }

        return stack_out
    
    @torch.no_grad()
    def generate(self,pre_compute_item,max_new_tokens,num_beams):
        inputs_embeds = pre_compute_item['inputs_embeds']
        attention_mask = pre_compute_item['attention_mask']
    
        out = self.mt5_model.generate(inputs_embeds = inputs_embeds,
                                attention_mask = attention_mask,
                                max_new_tokens=max_new_tokens,
                                num_beams = num_beams,
                            )

        return out



class SignetExpert(nn.Module):
    def __init__(self, args):
        super().__init__()
        self.args = args
        
        self.modes = ['body', 'left', 'right', 'face_all']
        
        self.graph, A = {}, []
        # project (x,y,score) to hidden dim
        hidden_dim = args.hidden_dim
        self.proj_linear = nn.ModuleDict()
        for mode in self.modes:
            self.graph[mode] = Graph(layout=f'{mode}', strategy='distance', max_hop=1)
            A.append(torch.tensor(self.graph[mode].A, dtype=torch.float32, requires_grad=False))
            self.proj_linear[mode] = nn.Linear(3, 64)

        self.gcn_modules = nn.ModuleDict()
        self.fusion_gcn_modules = nn.ModuleDict()
        spatial_kernel_size = A[0].size(0)
        # print(spatial_kernel_size)
        # exit()
        for index, mode in enumerate(self.modes):
            self.gcn_modules[mode], final_dim = get_stgcn_chain(64, 'spatial', (1, spatial_kernel_size), A[index].clone(), True)
            self.fusion_gcn_modules[mode], _ = get_stgcn_chain(final_dim, 'temporal', (5, spatial_kernel_size), A[index].clone(), True)
        
        self.gcn_modules['left'] = self.gcn_modules['right']
        self.fusion_gcn_modules['left'] = self.fusion_gcn_modules['right']
        self.proj_linear['left'] = self.proj_linear['right']

        self.part_para = nn.Parameter(torch.zeros(hidden_dim*len(self.modes)))
        self.pose_proj = nn.Linear(256*4, 768)
        
        self.apply(self._init_weights)
        
        if "CSL" in self.args.dataset:
            self.lang = 'Chinese'
        elif "Phoenix" in self.args.dataset:
            self.lang = 'German'
        else:
            self.lang = 'English'
        
    
    
    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def maybe_autocast(self, dtype=torch.float32):
        # if on cpu, don't use autocast
        # if on gpu, use autocast with dtype if provided, otherwise use torch.float16
        # enable_autocast = self.device != torch.device("cpu")
        enable_autocast = True

        if enable_autocast:
            return torch.cuda.amp.autocast(dtype=dtype)
        else:
            return contextlib.nullcontext()


    def forward(self, src_input, tgt_input):
        
        # Pose branch forward
        features = []
        pool_features_dict = {}  # Store pool features for each body part

        body_feat = None
        for part in self.modes:
            # project position to hidden dim
            proj_feat = self.proj_linear[part](src_input[part]).permute(0,3,1,2) #B,C,T,V
            # print(part, proj_feat.shape)
            # spatial gcn forward
            gcn_feat = self.gcn_modules[part](proj_feat)
            if part == 'body':
                body_feat = gcn_feat

            else:
                assert not body_feat is None
                if part == 'left':
                        
                    gcn_feat = gcn_feat + body_feat[..., -2][...,None].detach()
                    
                elif part == 'right':
                        
                    gcn_feat = gcn_feat + body_feat[..., -1][...,None].detach()

                elif part == 'face_all':
                    gcn_feat = gcn_feat + body_feat[..., 0][...,None].detach()

                else:
                    raise NotImplementedError
            
            # temporal gcn forward
            gcn_feat = self.fusion_gcn_modules[part](gcn_feat) #B,C,T,V
            pool_feat = gcn_feat.mean(-1).transpose(1,2) #B,T,C
            # print(part, pool_feat.shape)
            
            # Store pool feature for this body part
            pool_features_dict[part] = pool_feat
            features.append(pool_feat)
        
        # concat sub-pose feature across token dimension
        inputs_embeds = torch.cat(features, dim=-1) + self.part_para
        inputs_embeds = self.pose_proj(inputs_embeds)
        
        pool_features_part = []
        for part in ['left', 'right']:
            pool_feat = pool_features_dict[part]
            # print('x_global', part, pool_feat.shape)
            part_global = pool_feat.mean(dim=1)   # [B, C]
            pool_features_part.append(part_global)
        
        # final x_global = concat across parts
        x_global = torch.cat(pool_features_part, dim=-1)  # [B, num_parts*C]
        
        stack_out = {
            # use for inference
            'encoder_embeds': inputs_embeds,  # Dictionary with pool features for each body part
            'x_global': x_global,
        }

        return stack_out


    
class SignetGate(nn.Module):
    def __init__(self, args, num_experts=2, k=2):
        super().__init__()
        self.args = args
        self.num_experts = num_experts
        self.k = k
        
        self.modes = ['body', 'left', 'right', 'face_all']
        # hidden_dim = 512 * 2
        
        # # Router network (projects global pooled features to logits over experts)
        # self.router = nn.Sequential(
        # nn.Linear(hidden_dim, 128),
        # nn.ReLU(),
        # nn.Linear(128, num_experts)
        # )
        hidden_dim = 512  # size of each x_global from expert

        # Router remains the same
        self.router = nn.Sequential(
            nn.Linear(hidden_dim, 128),
            nn.ReLU(),
            nn.Linear(128, num_experts)
        )
        
        # Learnable query for attention aggregation
        # self.gate_query = nn.Parameter(torch.randn(1, 1, hidden_dim)) # this is for the static router
        self.query_mlp = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim)
        )
        self.gate_norm = nn.LayerNorm(hidden_dim)
        
        # adding expert adapter
        self.adapters = nn.ModuleList([
            ExpertAdapter(hidden_dim=768, rank=16, dropout=0.1)
            for _ in range(num_experts)
            ])

        
        
        self.apply(self._init_weights)
        
        if "CSL" in self.args.dataset:
            self.lang = 'Chinese'
        elif "Phoenix" in self.args.dataset or "DGS" in self.args.dataset:
            self.lang = 'German'
        else:
            self.lang = 'English'
        
        self.mt5_model = MT5ForConditionalGeneration.from_pretrained(mt5_path)
        self.mt5_tokenizer = T5Tokenizer.from_pretrained(mt5_path, legacy=False)
        


        if args.use_lora:
            lora_config = LoraConfig(
                            r=args.lora_rank,                         # Rank
                            lora_alpha=args.lora_alpha,               # Scaling factor
                            target_modules=["q", "v"],                # LoRA target layers
                            lora_dropout=args.lora_dropout,
                            bias="none",
                            task_type=TaskType.SEQ_2_SEQ_LM
                        )
            self.mt5_model = get_peft_model(self.mt5_model, lora_config)
            # 1 Freeze everything first
            for param in self.mt5_model.parameters():
                param.requires_grad = False

            # 2 Unfreeze only encoder LoRA parameters
            for name, param in self.mt5_model.named_parameters():
                if "lora" in name and "encoder" in name:
                    param.requires_grad = True

            # 3 Unfreeze only the *base* decoder parameters (not LoRA)
            for name, param in self.mt5_model.named_parameters():
                if "decoder" in name and "lora" not in name:
                    param.requires_grad = True
    
        
    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def maybe_autocast(self, dtype=torch.float32):
        # if on cpu, don't use autocast
        # if on gpu, use autocast with dtype if provided, otherwise use torch.float16
        # enable_autocast = self.device != torch.device("cpu")
        enable_autocast = True

        if enable_autocast:
            return torch.cuda.amp.autocast(dtype=dtype)
        else:
            return contextlib.nullcontext()

    def topk_gating(self, x_global, expert_outputs, temperature=1.0):
        """x_global: [B, D] global summary"""
        # print(x_global.shape)
        logits = self.router(x_global)  # [B, num_experts]

        if self.training:
            # print("Using stochastic Gumbel-Softmax gating during training.")
            # Training: stochastic Gumbel-Softmax
            weights = F.gumbel_softmax(logits, tau=temperature, hard=False)  # [B, num_experts]
            
            # Weighted mixture of all experts (encourages exploration)
            fused = 0
            for i, expert in enumerate(expert_outputs):
                w = weights[:, i].unsqueeze(-1).unsqueeze(-1)  # [B,1,1]
                fused = fused + w * expert
            topk_idx = torch.topk(logits, self.k, dim=-1).indices  # just for monitoring
        else:
            # Evaluation: deterministic Top-k
            topk_vals, topk_idx = torch.topk(logits, self.k, dim=-1)  # [B, k]
            gate_weights = F.softmax(topk_vals, dim=-1)               # [B, k]

            B, T, H = expert_outputs[0].shape
            fused = torch.zeros(B, T, H, device=expert_outputs[0].device)

            for i in range(self.k):
                idx = topk_idx[:, i]   # [B]
                w = gate_weights[:, i] # [B]
                # Batch gather: select embeddings from expert_outputs[idx[b]] for each b
                selected = torch.stack([expert_outputs[j][b] for b, j in enumerate(idx)], dim=0)
                fused += w.unsqueeze(-1).unsqueeze(-1) * selected

            weights = gate_weights  # [B, k]

        return fused, topk_idx, weights
    
    def aggregate_experts_attention_static(self, expert_globals):
        """expert_globals: [B, N, D]"""
        B, N, D = expert_globals.shape

        # Broadcast the learnable query
        query = self.gate_query.expand(B, 1, D)  # [B, 1, D]

        # Compute attention over experts
        attn_logits = (query @ expert_globals.transpose(1, 2)) / math.sqrt(D)  # [B, 1, N]
        attn_weights = torch.softmax(attn_logits, dim=-1)                      # [B, 1, N]

        # Weighted combination of expert globals
        x_global = (attn_weights @ expert_globals).squeeze(1)                  # [B, D]

        # Normalize output for stability
        x_global = self.gate_norm(x_global)
        return x_global, attn_weights
    
    
    def aggregate_experts_attention(self, expert_globals):
        """Aggregate multiple expert-level global features into a single vector using"""
        B, N, D = expert_globals.shape

        # Create data-dependent query
        # Query is computed from the mean expert feature per sample.
        avg_global = expert_globals.mean(dim=1)  # [B, D]
        query = self.query_mlp(avg_global).unsqueeze(1)  # [B, 1, D]

        # Compute attention logits
        attn_logits = torch.bmm(query, expert_globals.transpose(1, 2))  # [B, 1, N]
        attn_logits = attn_logits / math.sqrt(D)

        # Optional: normalize for numerical stability
        attn_logits = attn_logits - attn_logits.max(dim=-1, keepdim=True)[0]

        # Softmax across experts
        attn_weights = torch.softmax(attn_logits, dim=-1)  # [B, 1, N]
        attn_weights = F.dropout(attn_weights, p=0.1, training=self.training)

        # Weighted sum of expert globals
        x_global = torch.bmm(attn_weights, expert_globals).squeeze(1)  # [B, D]

        # Normalize for stability
        x_global = self.gate_norm(x_global)

        return x_global, attn_weights.squeeze(1)
    
    def forward(
        self,
        inputs_of_experts,
        tgt_input,
        input_attention_mask,
        task="SLT",
        **kwargs
    ):
        if task == "contrastive_loss":
            return self._forward_contrastive(inputs_of_experts, tgt_input, input_attention_mask, **kwargs)
        elif task == "contrastive_ablation_loss":
            return self._forward_contrastive_ablation(inputs_of_experts, tgt_input, input_attention_mask, **kwargs)
        elif task == "sinkhorn_loss":
            return self._forward_sinkhorn(inputs_of_experts, tgt_input, input_attention_mask, **kwargs)
        elif task == "SLT":
            return self._forward_translation(inputs_of_experts, tgt_input, input_attention_mask, **kwargs)
        elif task == "ablation_SLT":
            return self._forward_ablation(inputs_of_experts, tgt_input, input_attention_mask, **kwargs) 
        else:
            raise ValueError(f"Unknown task type: {task}")
        
    def _forward_contrastive(self, inputs_of_experts, tgt_input, input_attention_mask, temperature=1.0, contrastive_weight=1.0):
        """inputs_of_experts: list of dicts from experts"""

        # 1 Gating Fusion
        # globals = [exp['x_global'] for exp in inputs_of_experts] # list of [B, D]
        # x_global = torch.cat(globals, dim=-1) # [B, num_experts*D]
        expert_globals = torch.stack([exp['x_global'] for exp in inputs_of_experts], dim=1)  # [B, N, D]
        # expert_outputs = [exp['encoder_embeds'] for exp in inputs_of_experts] # list of [B, T, H]
        expert_outputs = []
        for i, exp in enumerate(inputs_of_experts):
            out = exp['encoder_embeds']          # [B, T, H]
            adapted_out = self.adapters[i](out)  # apply LoRA-style adapter
            expert_outputs.append(adapted_out)
        
        # Attention-based aggregation
        x_global, attn_weights = self.aggregate_experts_attention(expert_globals)  # [B, D]

        fused_embeds, topk_idx, gate_weights = self.topk_gating(x_global, expert_outputs)
        inputs_embeds = fused_embeds  # [B, T, H]

        # 2 Get text embeddings (precomputed)
        text_embeds = tgt_input["text_embeddings"].to(inputs_embeds.device).float()  # [B, H]

        # 3 Pass video embeddings through mT5 encoder
        # The goal is to align the *encoded* video features with text embeddings
        video_encoded_out = self.mt5_model.encoder(
            inputs_embeds=inputs_embeds,
            attention_mask=input_attention_mask,
            return_dict=True
        )
        video_encoded = video_encoded_out.last_hidden_state.mean(dim=1)  # [B, H]

        # 4 Normalize both for contrastive alignment
        video_encoded = F.normalize(video_encoded, dim=-1)
        text_embeds = F.normalize(text_embeds, dim=-1)

        # 5 Learnable temperature scaling
        if not hasattr(self, "logit_scale"):
            self.logit_scale = torch.nn.Parameter(torch.ones([]) * np.log(1 / 0.07))
        scale = self.logit_scale.exp()

        # 6 Compute similarity matrix
        # Ensure both are same dtype (use video_encoded's dtype)
        text_embeds = text_embeds.to(video_encoded.dtype)
        logits_per_video = (video_encoded @ text_embeds.t()) * scale
        logits_per_text = logits_per_video.t()
        targets = torch.arange(len(video_encoded), device=video_encoded.device)

        contrastive_loss = (
            F.cross_entropy(logits_per_video, targets) +
            F.cross_entropy(logits_per_text, targets)
        ) / 2

        # 9 Return outputs
        stack_out = {
            "contrastive_loss": contrastive_loss,
            "loss": contrastive_loss,
        }

        return stack_out
    
    def _forward_contrastive_ablation(self, inputs_of_experts, tgt_input, input_attention_mask, temperature=1.0, contrastive_weight=1.0):
        """inputs_of_experts: list of dicts from experts"""

        # 1 Gating Fusion
        # globals = [exp['x_global'] for exp in inputs_of_experts] # list of [B, D]
        # x_global = torch.cat(globals, dim=-1) # [B, num_experts*D]
        # expert_globals = torch.stack([exp['x_global'] for exp in inputs_of_experts], dim=1) # [B, N, D]
        # expert_outputs = [exp['encoder_embeds'] for exp in inputs_of_experts] # list of [B, T, H]
        expert_outputs = []
        for i, exp in enumerate(inputs_of_experts):
            out = exp['encoder_embeds']          # [B, T, H]
            adapted_out = self.adapters[i](out)  # apply LoRA-style adapter
            expert_outputs.append(adapted_out)
        
        # Attention-based aggregation
        # x_global, attn_weights = self.aggregate_experts_attention(expert_globals) # [B, D]

        # fused_embeds, topk_idx, gate_weights = self.topk_gating(x_global, expert_outputs)
        # inputs_embeds = fused_embeds # [B, T, H]
        inputs_embeds = expert_outputs[0]  # Ablation: use only the first expert

        # 2 Get text embeddings (precomputed)
        text_embeds = tgt_input["text_embeddings"].to(inputs_embeds.device).float()  # [B, H]

        # 3 Pass video embeddings through mT5 encoder
        # The goal is to align the *encoded* video features with text embeddings
        video_encoded_out = self.mt5_model.encoder(
            inputs_embeds=inputs_embeds,
            attention_mask=input_attention_mask,
            return_dict=True
        )
        video_encoded = video_encoded_out.last_hidden_state.mean(dim=1)  # [B, H]

        # 4 Normalize both for contrastive alignment
        video_encoded = F.normalize(video_encoded, dim=-1)
        text_embeds = F.normalize(text_embeds, dim=-1)

        # 5 Learnable temperature scaling
        if not hasattr(self, "logit_scale"):
            self.logit_scale = torch.nn.Parameter(torch.ones([]) * np.log(1 / 0.07))
        scale = self.logit_scale.exp()

        # 6 Compute similarity matrix
        # Ensure both are same dtype (use video_encoded's dtype)
        text_embeds = text_embeds.to(video_encoded.dtype)
        logits_per_video = (video_encoded @ text_embeds.t()) * scale
        logits_per_text = logits_per_video.t()
        targets = torch.arange(len(video_encoded), device=video_encoded.device)

        contrastive_loss = (
            F.cross_entropy(logits_per_video, targets) +
            F.cross_entropy(logits_per_text, targets)
        ) / 2

        # 9 Return outputs
        stack_out = {
            "contrastive_loss": contrastive_loss,
            "loss": contrastive_loss,
        }

        return stack_out

    def _forward_sinkhorn(self, inputs_of_experts, tgt_input, input_attention_mask,
                        epsilon=0.2, n_iter=40):
        """Sinkhorn OT alignment (batched, masked, stable)."""
        # 1) Fuse experts
        globals = [exp['x_global'] for exp in inputs_of_experts]
        x_global = torch.cat(globals, dim=-1)
        expert_outputs = [exp['encoder_embeds'] for exp in inputs_of_experts]
        fused_embeds, _, _ = self.topk_gating(x_global, expert_outputs)  # [B, Tv, H]
        video_embeds = fused_embeds
        video_mask   = input_attention_mask.float()  # [B, Tv]

        # 2) Text tokens + mask
        text_embeds = tgt_input["text_embeddings"].to(video_embeds.device)
        text_mask   = tgt_input["text_mask"].to(video_embeds.device).float()

        # 3) Encode video with mT5 encoder (optional but recommended)
        video_out = self.mt5_model.encoder(
            inputs_embeds=video_embeds,
            attention_mask=video_mask.long(),
            return_dict=True,
        )
        video_tokens = video_out.last_hidden_state  # [B, Tv, H]

        # 4) Normalize in float32
        # (also clamp norms to avoid zero-norm vectors)
        def safe_norm(x):
            x = x.float()
            x = x / (x.norm(dim=-1, keepdim=True).clamp_min(1e-6))
            return x
        video_tokens = safe_norm(video_tokens)
        text_embeds  = safe_norm(text_embeds)

        # 5) Build masked cosine distance
        # cost in [0,2], finite only on valid pairs
        sim  = torch.bmm(video_tokens, text_embeds.transpose(1, 2))       # [B, Tv, Tt]
        cost = torch.clamp(1.0 - sim, 0.0, 2.0)

        mask_v = video_mask.unsqueeze(-1)  # [B, Tv, 1]
        mask_t = text_mask.unsqueeze(1)    # [B, 1, Tt]
        valid  = (mask_v * mask_t) > 0     # [B, Tv, Tt], bool

        # set cost to +inf where invalid, so they never contribute
        cost = torch.where(valid, cost, torch.full_like(cost, float('inf')))

        # 6) Uniform marginals on valid tokens
        mu = mask_v / (mask_v.sum(dim=1, keepdim=True) + 1e-8)  # [B, Tv, 1]
        nu = mask_t / (mask_t.sum(dim=2, keepdim=True) + 1e-8)  # [B, 1, Tt]

        # 7) Sinkhorn (masked, stable)
        pi = stable_sinkhorn_masked(mu, nu, cost, valid, epsilon=epsilon, n_iter=n_iter)

        # 8) OT loss: masked average
        # Replace inf cost by 0 for multiplication (will be masked by pi anyway)
        cost_finite = torch.where(torch.isinf(cost), torch.zeros_like(cost), cost)
        denom = valid.float().sum(dim=[1,2]).clamp_min(1.0)  # avoid /0
        loss_per_sample = (pi * cost_finite).sum(dim=[1,2]) / denom
        loss_ot = loss_per_sample.mean()

        # Optional debug: masked mean cost and pi mean only over valid pairs
        with torch.no_grad():
            valid_cost_mean = (cost_finite * valid.float()).sum() / denom.sum()
            pi_mean = (pi * valid.float()).sum() / denom.sum()
            if torch.isnan(loss_ot) or loss_ot.item() == 0.0 or torch.isinf(loss_ot):
                print("[Sinkhorn Debug] eps=", float(epsilon),
                    " n_iter=", n_iter,
                    " masked_cost_mean=", float(valid_cost_mean),
                    " pi_mean=", float(pi_mean))

        return {"sinkhorn_loss": loss_ot, "loss": loss_ot}
    
    def _forward_translation(self, inputs_of_experts, tgt_input, input_attention_mask, temperature=1.0):
        """inputs_of_experts: list of dicts from experts"""
        
        # Prepare inputs for gating
        # globals = [exp['x_global'] for exp in inputs_of_experts] # list of [B, D]
        # # print(globals[0].shape)
        # x_global = torch.cat(globals, dim=-1) # [B, num_experts*D]
        expert_globals = torch.stack([exp['x_global'] for exp in inputs_of_experts], dim=1)  # [B, N, D]
        # expert_outputs = [exp['encoder_embeds'] for exp in inputs_of_experts] # list of [B, T, H]
        expert_outputs = []
        for i, exp in enumerate(inputs_of_experts):
            out = exp['encoder_embeds']          # [B, T, H]
            adapted_out = self.adapters[i](out)  # apply LoRA-style adapter
            expert_outputs.append(adapted_out)
        
        # Attention-based aggregation
        x_global, attn_weights = self.aggregate_experts_attention(expert_globals)  # [B, D]

        # Top-k gating
        fused_embeds, topk_idx, gate_weights = self.topk_gating(x_global, expert_outputs)
        inputs_embeds = fused_embeds  # [B, T, H]


        prefix_token = self.mt5_tokenizer(
                                [f"Translate sign language video to {self.lang}: "] * len(tgt_input["gt_sentence"]),
                                padding="longest",
                                truncation=True,
                                return_tensors="pt",
                            ).to(inputs_embeds.device)

        prefix_embeds = self.mt5_model.encoder.embed_tokens(prefix_token['input_ids'])
        inputs_embeds_prefix = torch.cat([prefix_embeds, inputs_embeds], dim=1)

        attention_mask = torch.cat([prefix_token['attention_mask'], input_attention_mask], dim=1)

        tgt_input_tokenizer = self.mt5_tokenizer(tgt_input['gt_sentence'], 
                                                return_tensors="pt", 
                                                padding=True,
                                                truncation=True,
                                                max_length=50)

        labels = tgt_input_tokenizer['input_ids']
        labels[labels == self.mt5_tokenizer.pad_token_id] = -100
        
        out = self.mt5_model(inputs_embeds = inputs_embeds_prefix,
                    attention_mask = attention_mask,
                    labels = labels.to(inputs_embeds_prefix.device),
                    return_dict = True,
                    )
        
        label = labels.reshape(-1)
        out_logits = out['logits']
        logits = out_logits.reshape(-1,out_logits.shape[-1])
        loss_fct = torch.nn.CrossEntropyLoss(label_smoothing=self.args.label_smoothing, ignore_index=-100)
        loss = loss_fct(logits, label.to(out_logits.device, non_blocking=True))

        stack_out = {
            # use for inference
            'inputs_embeds':inputs_embeds_prefix,
            'attention_mask':attention_mask,
            'loss':loss,
        }

        return stack_out

    def _forward_ablation(self, inputs_of_experts, tgt_input, input_attention_mask, temperature=1.0):
        """inputs_of_experts: list of dicts from experts"""
        
        # Prepare inputs for gating
        # globals = [exp['x_global'] for exp in inputs_of_experts] # list of [B, D]
        # # print(globals[0].shape)
        # x_global = torch.cat(globals, dim=-1) # [B, num_experts*D]
        # expert_globals = torch.stack([exp['x_global'] for exp in inputs_of_experts], dim=1) # [B, N, D]
        # expert_outputs = [exp['encoder_embeds'] for exp in inputs_of_experts] # list of [B, T, H]
        # print(type(inputs_of_experts))
        expert_outputs = []
        for i, exp in enumerate(inputs_of_experts):
            out = exp['encoder_embeds']          # [B, T, H]
            adapted_out = self.adapters[i](out)  # apply LoRA-style adapter
            expert_outputs.append(adapted_out)
        
        # Attention-based aggregation
        # x_global, attn_weights = self.aggregate_experts_attention(expert_globals) # [B, D]
        

        # expert_outputs = [exp['encoder_embeds'] for exp in inputs_of_experts] # list of [B, T, H]

        # Top-k gating
        # fused_embeds, topk_idx, gate_weights = self.topk_gating(x_global, expert_outputs)
        # inputs_embeds = fused_embeds # [B, T, H]
        inputs_embeds = expert_outputs[0]  # ablation: use only first expert
    

        prefix_token = self.mt5_tokenizer(
                                [f"Translate sign language video to {self.lang}: "] * len(tgt_input["gt_sentence"]),
                                padding="longest",
                                truncation=True,
                                return_tensors="pt",
                            ).to(inputs_embeds.device)

        prefix_embeds = self.mt5_model.encoder.embed_tokens(prefix_token['input_ids'])
        inputs_embeds_prefix = torch.cat([prefix_embeds, inputs_embeds], dim=1)

        attention_mask = torch.cat([prefix_token['attention_mask'], input_attention_mask], dim=1)

        tgt_input_tokenizer = self.mt5_tokenizer(tgt_input['gt_sentence'], 
                                                return_tensors="pt", 
                                                padding=True,
                                                truncation=True,
                                                max_length=50)

        labels = tgt_input_tokenizer['input_ids']
        labels[labels == self.mt5_tokenizer.pad_token_id] = -100
        
        out = self.mt5_model(inputs_embeds = inputs_embeds_prefix,
                    attention_mask = attention_mask,
                    labels = labels.to(inputs_embeds_prefix.device),
                    return_dict = True,
                    )
        
        label = labels.reshape(-1)
        out_logits = out['logits']
        logits = out_logits.reshape(-1,out_logits.shape[-1])
        loss_fct = torch.nn.CrossEntropyLoss(label_smoothing=self.args.label_smoothing, ignore_index=-100)
        loss = loss_fct(logits, label.to(out_logits.device, non_blocking=True))

        stack_out = {
            # use for inference
            'inputs_embeds':inputs_embeds_prefix,
            'attention_mask':attention_mask,
            'loss':loss,
        }

        return stack_out
    @torch.no_grad()
    def generate(self, pre_compute_item, max_new_tokens, num_beams):
        inputs_embeds = pre_compute_item['inputs_embeds']
        attention_mask = pre_compute_item['attention_mask']
    
        out = self.mt5_model.generate(inputs_embeds = inputs_embeds,
                                attention_mask = attention_mask,
                                max_new_tokens=max_new_tokens,
                                num_beams = num_beams,
                            )
        return out
    @torch.no_grad()
    def generate_new(
        self,
        pre_compute_item,
        max_new_tokens=50,
        num_beams=4,
        do_sample=False,
        top_p=0.9,
        top_k=50,
        temperature=1.0,
        return_text=False
    ):
        """Flexible generation function supporting greedy, sampling, and beam decoding."""
        inputs_embeds = pre_compute_item['inputs_embeds']
        attention_mask = pre_compute_item['attention_mask']

        generation_kwargs = {
            "inputs_embeds": inputs_embeds,
            "attention_mask": attention_mask,
            "max_new_tokens": max_new_tokens,
            "do_sample": do_sample,
            "top_p": top_p,
            "top_k": top_k,
            "temperature": temperature,
            "num_beams": (1 if do_sample else num_beams),
            "pad_token_id": self.mt5_tokenizer.pad_token_id,
            "eos_token_id": self.mt5_tokenizer.eos_token_id,
        }

        out = self.mt5_model.generate(**generation_kwargs)

        if return_text:
            # Decode into plain text
            decoded = self.mt5_tokenizer.batch_decode(out, skip_special_tokens=True)
            return decoded

        return out
    
def masked_logsumexp(x, mask, dim, keepdim):
    # x: [B, Tv, Tt], mask: same shape (1 for valid, 0 for padded)
    # substitute -inf where mask=0 so those positions don't contribute
    neg_inf = torch.finfo(x.dtype).min
    x_masked = torch.where(mask > 0, x, torch.full_like(x, neg_inf))
    return torch.logsumexp(x_masked, dim=dim, keepdim=keepdim)

def stable_sinkhorn_masked(mu, nu, cost, valid_mask, epsilon=0.2, n_iter=40):
    """Masked, numerically-stable batched Sinkhorn in log-space."""
    # work in float32 for stability
    mu   = mu.float()
    nu   = nu.float()
    cost = cost.float()
    M    = valid_mask.float()

    # guard: ensure each valid row/col has at least one valid partner
    # (rare, but can happen if a sample is empty after masking)
    row_has_valid = (M.sum(dim=2, keepdim=True) > 0).float()
    col_has_valid = (M.sum(dim=1, keepdim=True) > 0).float()
    M = M * row_has_valid * col_has_valid

    # duals
    u = torch.zeros_like(mu)
    v = torch.zeros_like(nu)

    for _ in range(n_iter):
        # u update: log mu - logsumexp_j [ (-C + v)/eps ] over valid j
        lse_v = masked_logsumexp((-cost + v) / epsilon, M, dim=2, keepdim=True)
        u = epsilon * (torch.log(mu + 1e-8) - lse_v) + u
        u = torch.nan_to_num(u, nan=0.0, posinf=0.0, neginf=0.0)

        # v update: log nu - logsumexp_i [ (-C + u)/eps ] over valid i
        lse_u = masked_logsumexp((-cost + u) / epsilon, M, dim=1, keepdim=True)
        v = epsilon * (torch.log(nu + 1e-8) - lse_u) + v
        v = torch.nan_to_num(v, nan=0.0, posinf=0.0, neginf=0.0)

    # transport plan: exp( (-C + u + v)/eps ), zero outside mask
    pi = torch.exp((-cost + u + v) / epsilon)
    pi = torch.where(M > 0, pi, torch.zeros_like(pi))
    pi = torch.nan_to_num(pi, nan=0.0, posinf=0.0, neginf=0.0)
    return pi


# Gated SIGNET fusion model
#
# Small expert adapter module
#
class ExpertAdapter(nn.Module):
    """Lightweight LoRA-style adapter applied after frozen expert outputs."""
    def __init__(self, hidden_dim, rank=16, dropout=0.1):
        super().__init__()
        self.norm = nn.LayerNorm(hidden_dim)
        self.dropout = nn.Dropout(dropout)
        
        # Low-rank decomposition (A down, B up)
        self.A = nn.Linear(hidden_dim, rank, bias=False)
        self.B = nn.Linear(rank, hidden_dim, bias=False)

        # Initialize near-zero so residual dominates at start
        nn.init.normal_(self.A.weight, std=1e-4)
        nn.init.zeros_(self.B.weight)

    def forward(self, x):
        """x: [B, T, H] or [B, H]"""
        residual = x
        x = self.norm(x)
        delta = self.B(self.A(x))
        return residual + self.dropout(delta)

#
# Top-k gating fusion block
#
    
#
# SIGNET Top-k Gated Mixture-of-Adapters
#

# ==============================
# Hierarchical Multi-Backbone Router
# ==============================


# ==============================
# SignetModel with Hierarchical Router + mT5
# ==============================

def get_requires_grad_dict(model):
    param_requires_grad = {name: True for name, param in model.named_parameters()}
    param_requires_grad_right = {}
    for key in param_requires_grad.keys():
        if 'left' in key:
            param_requires_grad_right[key.replace("left", 'right')] = param_requires_grad[key]
    param_requires_grad = {**param_requires_grad,
                           **param_requires_grad_right}
    params_to_update = {k: v for k, v in model.state_dict().items() if param_requires_grad.get(k, True)}

    return params_to_update

from torch.autograd import Function

# Gradient Reversal Layer


def grad_reverse(x, lambd=1.0):
    return GradReverse.apply(x, lambd)


# Bias Discriminator


# Bias Gates

# Modified SignetModel wrapper
